WCVendors/classes/admin/settings/sf-options.php, WCVendors/classes/class-vendors.php
Some stores (like mine) ship all products from one location and pay vendors a commission without giving them the shipping cost. 
There was already an option for tax, so I duplicated the necessary code for shipping. 
This has been tested :)
=> Created admin option for not giving shipping cost to vendor

classes/admin/class-admin-users.php
In short, for other custom post type you get the problem to no show others items.
see this : http://www.wcvendors.com/help/topic/custom-post-type-with-role-vendor
=> issue with others custom post type

classes/gateways/PayPal_AdvPayments/PayPal_AP/classes/adaptivepayments-sdk/lib/auth/PPAuth.php
Hit an error checking out in a sandbox. I believe the conflict is with the plugin "YITH WooCommerce Social Login" which I also require.
=> One last missing class_exists on PP OAuth declaration

class-wc-vendors.php
This would allow those who wish to do so to use the WP GitHub Updater.
=> Add GitHub Plugin URI for afragen/github-updater

classes/admin/class-vendor-admin-dashboard.php, classes/front/dashboard/class-vendor-dashboard.php
=> Vendor Mark Shipped Security Fix

classes/admin/class-admin-reports.php
date_i18n should be used for date and time internationalisation.
=> Using "date_i18n" instead of just "date"

classes/class-vendors.php
Makes the vendor child orders much more useful!
=> Store Vendor ID in vendor child order

templates/orders/orders.php
I want to add the hooks at before and after content.
=> Add the hook for vendor order content

classes/gateways/PayPal_AdvPayments/PayPal_AP/assets/icons/index.php, classes/gateways/PayPal_AdvPayments/PayPal_AP/assets/index.php, classes/gateways/PayPal_AdvPayments/PayPal_AP/classes/adaptivepayments-sdk/lib/auth/PPAuth.php, classes/gateways/PayPal_AdvPayments/PayPal_AP/classes/index.php, classes/gateways/PayPal_Masspay/api/lib/PPUtils.php, classes/gateways/PayPal_Masspay/api/lib/auth/PPAuth.php
=> Fix deprecated functions/constructor

classes/front/class-vendor-shop.php
=> Return 404 if vendor doesn't exist

classes/gateways/PayPal_AdvPayments/paypal_ap.php
The default translation file was affected as well.
_I could swear I had sent this PR before._
=> sprintf must be outside.

classes/includes/class-wcv-shortcodes.php
https://github.com/wcvendors/wcvendors/issues/418
=> Vendor featured product shortcode

classes/includes/class-wcv-shortcodes.php
https://github.com/wcvendors/wcvendors/issues/417
=> Top rated shortcode fix

classes/admin/settings/class-wcv-settings-display.php, classes/front/class-vendor-cart.php, classes/front/class-vendor-shop.php, templates/front/vendor-sold-by.php
Enhancement: https://github.com/wcvendors/wcvendors/issues/420
=> Sold by separator enhancement

class-wc-vendors.php
Issue: https://github.com/wcvendors/wcvendors/issues/427
=> Fix loading issue

classes/gateways/PayPal_AdvPayments/paypal_ap.php
Issue: https://github.com/wcvendors/wcvendors/issues/430
=> Convert yes/no to boolean

classes/admin/class-admin-reports.php
Issue: https://github.com/wcvendors/wcvendors/issues/432
=> Add previous order's tax and shipping when calculating totals for vendor

classes/admin/class-product-meta.php
Issue: https://github.com/wcvendors/wcvendors/issues/390
=> Assign media to vendor when assigning product

class-wc-vendors.php, classes/front/account/class-wc-account-links.php
https://github.com/wcvendors/wcvendors/issues/445
=> Fixed: Become a vendor goes to a 404

class-wc-vendors.php, classes/front/account/class-wc-account-links.php
Issue: https://github.com/wcvendors/wcvendors/issues/447
=> Fixed: my-account "become a vendor" tab is leading to a 404 #447

classes/admin/settings/class-wcv-settings-display.php, classes/class-install.php, classes/front/class-vendor-shop.php, classes/front/signup/class-vendor-signup.php, classes/includes/wcv-update-functions.php
Issue: https://github.com/wcvendors/wcvendors/issues/489
=> Added: Remove Ability to Register from the WP Login screen. #489

classes/front/class-vendor-shop.php
Issue: https://github.com/wcvendors/wcvendors/issues/500
=> Fixed: Logout issues

class-wc-vendors.php, classes/class-commission.php, classes/class-cron.php, classes/class-install.php, classes/class-queries.php, classes/class-shipping.php, classes/class-uninstall.php, classes/class-vendors.php
=> WordPress Coding Standards and general code cleanup

classes/class-commission.php
Issue: https://github.com/wcvendors/wcvendors/issues/499
=> Fixed: Commissions are calculated on integers

classes/admin/emails/class-wcv-vendor-notify-order.php, classes/includes/wcv-template-functions.php, templates/emails/plain/vendor-order-details.php, templates/emails/vendor-new-order.php, templates/emails/vendor-order-details.php
Issue: https://github.com/wcvendors/wcvendors/issues/487
=> Fixed: Coupon details not showing in vendor emails #487

classes/admin/emails/class-emails.php, classes/includes/wcv-template-functions.php
Trigger notification after submitting form if pro is active
=> Fixed: Vendor application firing before pro form submitted

class-wc-vendors.php, classes/class-queries.php, classes/front/dashboard/class-vendor-dashboard.php
Updated: Replace current PHP session with WC Session (Fix #514)
=> Use WC Session system

classes/admin/emails/class-emails.php, classes/admin/emails/class-wcv-vendor-notify-cancelled-order.php, templates/emails/plain/vendor-notify-cancelled-order.php, templates/emails/vendor-notify-cancelled-order.php, templates/emails/vendor-order-addresses.php
Issue: #518
- Added: new email type.
- Added: new email templates.
- Fixed: undefined `$show_customer_name` variable.
=> Added: Notify vendor when an order is marked as cancelled

classes/admin/settings/class-wcv-settings-capabilities.php
Issue: https://github.com/wcvendors/wcvendors/issues/526
=> Added: Filter for product data tabs

classes/admin/class-wcv-admin-settings.php
Fixed: Put description bellow textarea #535
=> Fixed: Put description below textarea #535

classes/admin/class-admin-menus.php
- Fix the commission table issue: the check column is too big in Firefox.
- Adjust column with of other columns so the table is nicer on typical screen resolutions.
=> Fixed: Commission table issue in Firefox

classes/front/dashboard/class-vendor-dashboard.php
Fixed: Saving some shortcodes get Update failed notice in Gutenberg #540
=> Fixed: Saving some shortcodes get Update failed notice in Gutenberg #540

classes/includes/class-wcv-shortcodes.php
=> Fixed: Vendor featured product shortcode display the same products for every vendor #553

classes/admin/views/html-vendor-settings-page.php
Various changes to fix #556 and improve the readability of the html-vendor-settings-page.php template.
Only the first commit is required to fix the issue.
=> Fix invalid vendor settings form markup

templates/emails/plain/vendor-notify-cancelled-order.php, templates/emails/plain/vendor-notify-order.php, templates/emails/vendor-order-addresses.php
=> Fixed: Email Issues #559

package-lock.json
This PR fixes the vulnerability in tar by upgrading its version in package-lock.json
=> Fixed: tar vulnerability

assets/js/admin/wcv-admin-commissions.js, class-wc-vendors.php, classes/admin/class-wcv-admin-setup.php, classes/admin/class-wcv-commissions-page.php
=> Added: Mark all commissions paid button #538

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Enhancement.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR adds PR and several issue templates to help us communicate better. The templates are taken from https://github.com/woocommerce/woocommerce with some modification.
Closes #564 .
This PR can be tested after it's merged to master only.
1. Create a new issue.
2. See 3 issue types.
3. Choose one type.
4. See the issue content is filled with the template content.
Repeat the process above for PR without step 2 and 3.
=> Added: Missing Issue templates #564

gulpfile.js, languages/wc-vendors.pot, package-lock.json, package.json
Update gulp script and version
Closes https://github.com/wcvendors/wcvendors/issues/584
=> Update gulp and build language file.

classes/front/class-vendor-cart.php, classes/front/class-vendor-shop.php, classes/includes/class-wcv-shortcodes.php, classes/includes/wcv-template-functions.php
closes #601
Closes #601
1. Check the sold by output on the front end to ensure they are all still linking correctly
2. Use the new filter to create an override ```wcv_sold_by_url```
=> Added: New template tag for sold by url

.circleci/config.yml, package-lock.json, package.json
=> Fixed: CircleCI

assets/js/admin/wcv-vendor-select.js, assets/js/wcv-admin-quick-edit.js, classes/admin/class-product-meta.php
Closes #604.
1. Have 3000 vendors and query monitor installed.
2. Click on Products in the backend.
3. See the page load quickly.
=> Fixed: Performance issue in WP-Admin area in large marketplaces #604

classes/class-install.php
This adds more capabilities to the vendor role ready to be used in the new updates
=> Updated: added capabilities required

languages/wc-vendors.pot
Add language file updates to release.
=> Update: language file

.gitattributes
Add's files / folders to the deploy ignore scripts
=> Deploy updates

classes/admin/class-wcv-admin-help.php
Updates out of date urls. 
Closes #622 .
=> Fixed: Urls

changelog.txt, class-wc-vendors.php, classes/admin/class-product-meta.php, languages/wc-vendors.pot, package.json, readme.txt
=> Release v2.1.18

changelog.txt, class-wc-vendors.php, package.json, readme.txt
Update tested WordPress and WooCommerce version.
WordPress 5.4
WooCommerce 4.0
=> Updated tested WP and WC Versions

composer.lock, src/Admin/Settings/Display.php, src/Admin/Settings/General.php
Migrate the existing admin settings to the new format 
Closes #631.
1. Check the settings are the same across old and new.
=> Migrate: Admin settings

class-wc-vendors.php
Tested order, vendor dashboard, commissions and various front end areas all looks good.
=> Updated: Tested to WooCommerce 4.1

changelog.txt, class-wc-vendors.php, languages/wc-vendors.pot, package.json, readme.txt
Release 2.2.20 
Please test that emails and fixes are working as expected.
=> Release v2.2.20

classes/admin/class-product-meta.php
Append vendor parameter to `posts_clauses` to filter allow filtering product list by the vendor. Get selected vendor id and preselect the vendor in the vendor dropdown field in the Products page.
Closes #657 
1. Go to wp-admin > Products page
2. Click on the vendor dropdown labelled -- No Change --
3. Type to search for a vendor selected a vendor once the dropdown is populated
4. Click the 'Filter' button to apply
5. After page load. Check the selected vendor is still selected in the vendor drop-down page.
6. Check that the listed products belong to the selected vendor.
=> Fixed: Filter Products by vendor in Wordpress dashboard not working #657

classes/class-vendors.php, classes/front/orders/class-export-csv.php
Update any deprecated calls. 
Fixes a couple of deprecated WooCommerce calls, tested jQuery for 5.5 support. 
Closes #673
=> Added: Support for WC4.4 and WP5.5

changelog.txt, class-wc-vendors.php, languages/wc-vendors.pot, package-lock.json, package.json, readme.txt
This will release v2.2.0 
Closes #675 .
1. Check all things in the changelog have been tested and working
=> Prepare v2.2.0

classes/admin/class-wcv-admin-import-export.php
The WooCommerce importer is not built with Marketplace in mind so it assumes the person importing the products is the owner and so does not check the post_author against the current vendor before importing.
Add checks to verify the currently logged in user (vendor) owns the products being imported before allowing updating. If the post_author and vendor_id do not match, we skip importing that particular product. Also, prevent the product data store from creating a default empty product if the data was not set.
Closes #670
1. Go to 'Products'
2. Click on 'Import'
3. Select the CSV file you wish to import
4. Provide an ID to update an existing product
5. The product must not be imported/updated if that product is owned by another vendor.
=> Fixed: Native CSV importer #670

changelog.txt, class-wc-vendors.php, package.json, readme.txt
Release 2.2.1
Please test all the fixes are working as expected.
=> Release v2.2.1

classes/admin/class-product-meta.php
Closes #701 .
1. Log in to wp-admin.
2. Go to the Product listing page.
3. Check for the vendor filter dropdown.
=> Updated: Update vendor drop downs place holder #701

changelog.txt, class-wc-vendors.php, languages/wc-vendors.pot, package-lock.json, package.json, readme.txt
Prepare version 2.2.2 for release 
- Temporarily disable import-export integration.
=> Prepare version 2.2.2

readme.txt
=> Updated: links in readme

templates/emails/vendor-order-details.php
Closes #731 
1. Run local test environment in php8
2. Test all aspects of customer and vendor experience
3. See it all is working without errors or warnings.
=> Php8 compatibility 

class-wc-vendors.php, classes/admin/class-admin-reports.php, classes/admin/views/html-admin-page-extensions.php
More php8 fixes. 
1. This removes warnings and fatal errors related to dates in the existing reports. 
2. Also re-enables the import/export tool for admins.
=> Php8 fixes

class-wc-vendors.php, classes/admin/class-admin-menus.php, classes/admin/class-wcv-commissions-csv-exporter.php, classes/admin/class-wcv-commissions-page.php
This adds a new column to the commissions page and the related export for showing that the product has been shipped
Closes #740.
1. Load commissions page
2. see new shipped column 
3. Export also works.
=> Added: New column on commissions page for shipped

changelog.txt, class-wc-vendors.php, languages/wc-vendors.pot, package-lock.json, package.json, readme.txt
=> Release 2.2.4

classes/admin/class-vendor-admin-dashboard.php, classes/class-queries.php
New filters to allow developers to modify the orders query.
1.
2.
3.
=> add new filter to allow custom order visibilities

templates/dashboard/orders.php
Closes #757 .
1. Change WC_Product to use wc_get_product.
2. Needs shipping state consistency.
=> Fixed: Errors in order template #757

assets/js/admin/wcv-admin-commissions.js, class-wc-vendors.php, classes/admin/class-wcv-commissions-page.php, tests/acceptance/DeleletCommissionCest.php
Closes #762 .
1.
2.
3.
* [x ] Have you successfully run tests with your changes locally?
=> Add: Delete commission row

classes/admin/class-wcv-commissions-page.php, classes/admin/settings/class-wcv-settings-display.php, readme.txt
There were a number of typos in the code, this addresses them.
=> Fixes various strings in the codebase

classes/admin/class-admin-reports.php, classes/admin/settings/class-wcv-settings-advanced.php, classes/admin/settings/class-wcv-settings-capabilities.php, classes/admin/settings/class-wcv-settings-display.php
Update the UI to use title case for the UI settings titles. 
Closes #759.
1. Navigate the interface and find that all settings UI titles have been updated to use title case
=> Updated: UI titles to use title case

classes/front/class-vendor-shop.php
=> Fixed: Duplicate seller info in single product page. #780

changelog.txt, class-wc-vendors.php, languages/wc-vendors.pot, package-lock.json, package.json, readme.txt
Prepare v2.3.1 for release
Close #782
=> Prepare v2.3.1 for release

inc/core-functions.php, inc/vendor-functions.php, src/Admin/Users.php, src/Admin/Vendor/Menus.php, src/Admin/Vendor/Orders.php, src/Admin/Vendor/OrdersTable.php, src/Admin/Vendor/SettingsPage.php, src/Admin/views/html-vendor-settings-page.php, src/Plugin.php, src/Vendor/Vendor.php
Added: New Marketplace menu for Vendor in Admin Dashboard and Pagination for orders table
1. Login as Vendor
2. Go to your site admin dashboard, e.g: https://examplesite.com/wp-admin
3. See Marketplace menu hover on Marketplace and view see Orders, Shop Settings, Products, Media. 
- Make orders table sortable
=> Migrate new Marketplace menu in Admin Dashboard For V3 #795

classes/class-queries.php
Closes #815.
1. Login as Vendors account
2. Go to Vendors Dashboard
3. See no notices
=> Fixed: Undefined variable ids

templates/dashboard/reports.php
change the td tag colspan="5" to match with th tag.
=> Fixed: The colspan does not match in vendor dashboard

classes/admin/class-vendor-admin-dashboard.php
Closes #843 .
1. Login as an Admin account
2. Goto WordPress Dashboard
3. See The Shop Settings and the Orders are disabled
=> Fixed: Vendor menu show on Admin dashboard

.eslintrc.js, .stylelintrc, gulpfile.js, package.json
Closes #841.
Updated start, build, dev script
=> Updated: Dev tools

classes/admin/class-setup-wizard.php, classes/admin/settings/class-wcv-settings-capabilities.php, classes/includes/wcv-update-functions.php, wpml-config.xml
Closes # .
1. Added capability for commission module.
2. in capability section added checkbox for disable or enable export commission button.
WP-admin->WC Vendors->Settings- >capabilities ->General->Export Commission
=> vendor commission

composer.json, composer.lock, phpunit.xml.dist, src/VendorOrder.php, tests/Unit/Order/VendorOrderTest.php, tests/Unit/bootstrap.php
Closes #698  . 
- `create_order_shipping_lines`
- `create_order_coupon_lines`
- `set_commission_paid`
- `get_commission_paid`
- `set_total_tax`
- `set_shipping_total`
- `set_shipping_tax`
- `set_discount_total`
- `set_discount_tax`
- Add unit test
=> Added: New functionality for VendorOrder object #698

classes/admin/class-setup-wizard.php
=> remove debug code

classes/admin/class-wcv-commissions-paypal-csv-exporter.php, classes/includes/class-wcv-shortcodes.php
Escape attributes that address a reported security vulnerability.            
Closes #881.
=> Fixed: Escaped attributes to address security vulnerability report

changelog.txt, class-wc-vendors.php, package-lock.json, package.json, readme.txt
Version 2.4.5 - 6th January 2023
* Fixed: Escaped attributes to address security vulnerability report (#882)
=> Prepare for v2.4.5 release
