wcvendors/wcvendors

classes/class-vendors.php

Currently, `is_vendor` only checks the user's first role to see if it is assigned to "vendor". I personally like keeping WP's user roles intact, so I append the Vendor role to a user, similar to how bbPress creates roles in addition to WP's.
Doing this allows me to have someone be an Author and also a Vendor. I want to assign vendors without affecting their ability to author posts. This change simply makes sure that `is_vendor` checks the entire user role array for the value, instead of assuming that the role is assigned in the first value. This change should only add flexibility to the code, without breaking anything.

Check all user roles when determining if user is a vendor

---

classes/gateways/PayPal_AdvPayments/paypal_ap.php

On line #376, the Instant Payment Notification URL sent to PayPal is forced to use HTTP even if the site uses an SSL certificate.
This presents a problem for websites that use SSL and Server Name Indication (SNI). All modern web browsers are sophisticated enough to handle SNI, however some remote calls made by applications (such as PayPal's IPN) are not able to find a route to the host because they are not able to be redirected appropriately. This is likely a security issue (unconfirmed).
Long story short, is it necessary to always force the URL to NOT use HTTPS? What is the benefit in this? For my site and anyone else using SNI this breaks IPN functionality.
This has been tested on my live site and has proven to fix IPN issues.
About SNI:
"SNI is a transport layer security extension …

Remove Forced HTTP Protocol on Sent IPN URL

---

class-wc-vendors.php
classes/front/dashboard/class-vendor-dashboard.php

I've tested it on my test server. And it works. Varnish + CDN services are affected. Default action for them is if any cookie exists page is non-cacheable. If you are stripping cookie PHPSESSID (in varnish configuration and forcing cache), php script can't use sessions (and some pages will be cached, but they shouldn't be in cache)
Before patch:
$ curl -I http://xxx.xxx/shop
.....
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=........; path=/
.....
After patch:
$ curl -I http://xxx.xxx/shop
.....
Cache-Control: max-age=3600
Expires: Thu, 05 Nov 2015 00:04:29 GMT
No Set-Cookie in the header

session fix

---

classes/admin/class-vendor-admin-dashboard.php

Code to fix for issue #231 seems to cause odd behavior in vendor orders admin page.
`PHP Fatal error: Call to undefined method WP_Post::get_attributes() in docroot/wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 93`
$_product passed to wc_attribute_label() is not WooCommerce product and doesn't have get_attributes() method here: https://github.com/wcvendors/wcvendors/blob/master/classes/admin/class-vendor-admin-dashboard.php#L473
This change passes proper WooCommerce product as parameter and collects meta table to return data instead of just echoing it to top of the page.

Fixed vendor order admin product attribute fetch and returning HTML

---

classes/gateways/PayPal_AdvPayments/paypal_ap.php

This is a follow up to commit e079ec2.
There is a regression since new WooCommerce update that breaks my fix. They have added a get_cancel_order_url_raw() methor for payment gateways that return clean unescaped URLs. Using this method now fixes the issue the clean way.

Fixed HTML escaped characters in Cancel and Return URLs

---

templates/dashboard/links.php

I need to add a link to the Free Dashboard... afaik, the only hook there is
do_action( 'wcvendors_before_dashboard' );
Which places a new link above the other links.
Solution: Adding a new hook

added hook in links template

---

class-wc-vendors.php

Now, init action opens sessions at each page, adding is_user_logged_in() in the condition will start session only if user is logged. It will help for varnish cache because PHPSESSID cookie blocks some CDN, varnish, etc...

Don't start session if user isn't logged

---

classes/admin/class-vendor-admin-dashboard.php

Product metadata in vendor admin order list was loaded with product id instead of order item id causing metadata from completely different product to be displayed in order list.
Order item ids are available from WC_Order->get_items() call which are now used.

Fix for vendor order admin product metadata loading

---

classes/admin/class-admin-page.php

Adding extensibility to wcVendors commissions management process through filters and actions so that other plugin developers can hook in and add actions to the "Bulk Actions" dropdown menu.

Extend commissions management process

---

classes/class-vendors.php

I got this error at the cart when I had two products in my cart; one with specific vendor, one without;
```
PHP Notice:  Trying to get property of non-object in wp-content/plugins/wc-vendors/classes/class-vendors.php on line 402
```

Prevent PHP notice for getting non-existing vendor name

---

classes/class-vendors.php

This will allow additional items to be added to the $receiver array.  Necessary for compatibility with store credit plugins.

Apply filter to get_vendor_dues_from_order() func

---

classes/admin/class-admin-reports.php

Issue: https://github.com/wcvendors/wcvendors/issues/456
The textbox is using the Chosen library which was replaced by Select2 so it was not getting the list of products.

Fixed: Commission by Product report is not functioning

---

classes/gateways/PayPal_AdvPayments/paypal_ap.php

For the Adaptive Payments IPN, if the vendor commission is set to 100%, the status sent by PayPal is `Completed`. If the commission is less than 100%, and the money gets sent to 2 or more PayPal addresses the status is `COMPLETED`.
This causes the order to be marked as Failed in WooCommerce although the payment went through.
PayPal will most likely not change this as the Adaptive Payments are no longer supported.

Handle PayPal Adaptive Payments IPN status inconsistencies

---

classes/class-vendors.php

Treat a single product page as a vendor page. This will allow the vendor widgets to be displayed on single product pages, for instance, the store contact widget should be displayed on single product pages to allow user to be able to contact the vendor from the product page.

Updated: Treat product as vendor page if product author is vendor

---

classes/class-shipping.php

The function calculate_shipping_tax calculates shipping tax based on provided $order details. On the product shipping tab, we do not have the $order so we use Geolocation to get customer country instead of getting it from order details.

Updated: Calculate tax without order details by geolocating user

---

classes/class-commission.php

Fix introduced in wcvendors/wcvendors#499 breaks shipping value float support.
This aim to format shipping value as a float like it's done elsewhere. BTW, regarding initial comment on the issue, the initial proposal was to set as string, but I guess float is better since aligned with other values.

Fixed: Shipping is saved in db as integer.

---

classes/includes/class-wcv-shortcodes.php

Used return instead of echoing the shortcode content, added support for overrides.
Issue:  #544

Fixed: Shortcode not showing in container when used in page builders

---

classes/admin/class-vendor-admin-dashboard.php

Original repoter: https://wordpress.org/support/topic/i-can-not-save-bank-account-number/#post-11636550
The user meta name of the saving method is wrong. That leads to vendor can't edit bank account number in the WordPress dashboard. This PR correct that name so the vendor can edit bank account number in the WP dashboard.

Fix wrong user meta name for bank account number

---

classes/front/class-vendor-cart.php

Add new filter `wcvendors_cart_sold_by_meta_template` which is set to `%1$s %2$s %3$s<br/>` by default. Developer can hook into this filter to change how sold by meta is display.
Closes #546.

Fixed: Sold by filters have space in them #546

---

classes/admin/emails/class-emails.php
classes/admin/emails/class-wcv-admin-notify-approved.php
classes/admin/emails/class-wcv-vendor-notify-application.php
classes/admin/emails/class-wcv-vendor-notify-approved.php
templates/emails/admin-notify-approved.php
templates/emails/plain/admin-notify-approved.php
templates/emails/vendor-notify-application.php
templates/emails/vendor-notify-approved.php

Added new email in 'WooCommerce > Settings > Emails' and a template for this email content. This email must be enabled in order to also send notification to admin when approving a user to be a vendor.
Also rephrased the existing vendor notification as some messages seem directed to vendor but sent to vendor.
Closes #578 .
1. Go to 'WooCommerce > Settings > Emails' and enable the 'Admin notify vendor approved' email. Click 'Manage' for this email to modify the defaults.
2. Go to WordPress admin Users > All Users', click approve for any pending vendor application
3. Check email or email log and an email should be received with a subject like [WC Vendors Free] <username> has been approved to be a vendor'

Fixed: Approving a vendor sends an email to the admin #578

---

assets/js/wcv-admin-quick-edit.js
class-wc-vendors.php

Added a script to check if the capability is disabled for the user and then hide the inputs so that the vendor cannot be able to select if they don't have the capability.
Closes #583  .
1. Edit option  'WC Vendors > Settings > Capabilities > Products - Featured Products'. Uncheck (if checked or leave unchecked) the option to disallow vendor to choose featured products, save the settings.
2. As a vendor add new product or view products on the vendor dashboard which will redirect to the WordPress Admin dashboard.
3. Using Quick Edit or 'Bulk Action > Edit'. If the 'Featured Products' in step 1 is not checked then the 'Featured' option in Quick Edit or Bulk Actions > Edit must not be visible.
4. Undo step 1, if the option is now checked, then the Featured options in Quick Edit and Bulk …

Fixed: Vendors can select featured #583

---

class-wc-vendors.php
classes/admin/class-vendor-admin-dashboard.php
classes/admin/settings/class-wcv-settings-display.php
classes/front/account/class-wc-account-links.php
classes/front/class-vendor-cart.php
classes/front/class-vendor-shop.php
classes/front/signup/class-vendor-signup.php
classes/includes/class-functions.php
classes/includes/class-wcv-shortcodes.php

Wrapped all labels in the WordPress translation functions to ensiure labels retrived from database go through i18n functions to be checked against translations before being output on the page.
Closes #579 .
1. Go to 'WC Vendors > Settings > Display > Labels' and change any of the labels
2. Edit the translation file for the current locale on your site to Include the translations for the new labels.
3. Check the pages where those labels are displayed, the translations should be displayed instead of the default labels.
You may need to get new tstrings from the updated .pot file in this PR: https://github.com/wcvendors/wcvendors/pull/585

Fixed: Translated strings saved to database aren't translated on output #579

---

classes/admin/class-vendor-reports.php
classes/class-commission.php
classes/class-vendors.php

Added a new argument to pass the order item from which commissions is calculated. This will allow commission to be calculated from the item instead of product price.
Required by https://github.com/wcvendors/wcvendors-pro/pull/1085.
1. Checkout this branch and test https://github.com/wcvendors/wcvendors-pro/pull/1085

Added: New order item argument for commission calculation for 1085

---

classes/admin/emails/class-emails.php

This PR adds missing return statements to low stock and out of stock email recipient filters.
Closes #593.
1. Enable low stock emails
2. Install mail log plugin
3. Trigger low stock emails
4. See the low stock/out of stock emails sending normally.

Fixed:  Low/out stock emails not sending #593 

---

classes/front/class-vendor-cart.php
classes/includes/wcv-template-functions.php
templates/front/vendor-sold-by.php

Closes #597
1. Sold by label on single product page always had a space after label and separator
2. Check the sold by spacing on all aspects of the site are now universal with no space

Fixed: Sold by label spacing on single product page

---

classes/admin/class-wcv-admin-settings.php

Add a new action to 
Closes #619 
1. Must be tested with this PR: https://github.com/wcvendors/wcvendors/issues/619
2. There must be a new 'Reset to default' button in WC Vendors > Settings > Display > Branding

Added: New action hook to image field.

---

classes/includes/class-wcv-shortcodes.php

Replace show_products with has_products argument in wcv_pro_vendorslist shortcode. Add a deprecated argument notice to be logged when if the show_products argument is used.
Closes  #595
1. Add the shortcode [wcv_pro_vendorslist show_products="yes"] to any post/page
2. Visit the post and you should see the vendors list as normal
3. Check debug.log and you should see a message like
Notice: show_products was called with an argument that is <strong>deprecated</strong> since version 2.1.16! This argument will be removed in 3.0.0 in /var/www/html/wp-includes/functions.php
4. Replace the show_products="yes" with has_products="yes" in the shortcode, save the post.
5. View the post. The Vendors list should be displayed as normal.
6. Check debug.log, there should be no new log entry like the in …

Updated: Deprecate vendor_list shortcode argument #595

---

classes/admin/views/setup/header.php

Fixes error output with warnings in the setup wizard
Closes #640.
Ensure WP_DEBUG is on
1. Go to WC Vendors > Settings  
2. Click on help top right, then setup wizard
3. See error is gone.

Fixed: get current page error on setup wizard #640

---

classes/class-queries.php

Changes as proposed
> More specifically, I have to reverse the logic for this orders_within_range function so that it would SET the wcv_order_start_date and wcv_order_end_date session variables BEFORE it would GET them.
Closes #645.
1.  Go to 'Vendor Dashboard > Orders' page
2. Select a 'From:' and 'To:' date to filter the orders and click Show'
3. Check and see the displayed orders match the selected date range.

Fix date query bug.

---

classes/includes/class-wcv-shortcodes.php

Updated all filters in the WCV_Shortcodes to use the wcvendors prefix 'wcv'
Closes #644 .
1. For each of the filters add, apply them using the code snippet below, replacing FILTER_NAME with each of the filters
2. Visit the Vendors list page and see if the vendors displayed are matching the modified query args.
```
add_filter(
'FILTER_NAME',
function ( $args, $atts ) {
// modify $args
return $args;
}
);
```

Updated: Update filter names in WCV_Shortcodes class #644

---

classes/admin/class-admin-reports.php
classes/admin/class-wcv-admin-setup.php
classes/class-commission.php
templates/dashboard/date-picker.php
templates/orders/shipping/shipping-form.php

Use gmdate() to avoid runtime errors associated with date() function.
Closes #625 
1. Go to Settings > General - change the timezone to somewhere other than the server time.
2. Process order and complete it.
3. Check that the order time in WC Vendors > commission
4. The commission date must be the same as the WooCommerce order date

Fixed: Timezone display for commissions #625

---

classes/admin/class-admin-menus.php
classes/admin/class-wcv-commissions-csv-exporter.php
classes/admin/class-wcv-commissions-page.php
classes/class-commission.php
classes/includes/class-wcv-shortcodes.php

Replace month dropdown with date range fields.
Closes #649 .
1. Go to WC Vendors > Commissions
2. Check and confirm that the month dropdown is replaced with two fields labelled From: and To:
3. Select any date from the 'From' field and then another date in the 'To' field and do the following:
3a. Click on 'Filter' and confirm the commissions listed are from within the range selected
3b. Click on 'Export to CSV', save the CSV file, open it and confirm the exported commissions are within the specified range.
3c. Click on 'Export Totals to CSV' and confirm that the exported totals are calculated for the orders within the selected date range.

Added: Add date range filters for commissions #649

---

changelog.txt
class-wc-vendors.php
classes/front/class-vendor-shop.php

Closes #599.
1. Go to WCVendor settings > display ( Tab ) > Labels > Store Info
2.Check the box see store info tab shows on single product page
3. uncheck the box see store info tab no longer shows on single product page.

Fixed: Front-end issues of Store Info option 

---

classes/admin/class-admin-menus.php
classes/admin/class-wcv-commissions-page.php

Closes #660 .
1. Go to 'WordPress Dashboard > WC Vendors > Commissions'
2. Click on 'Screen Options' on the upper-right corner
3. Change pagination from 10 to any other.
4. Apply value will be shown in the Screen Option and the list will also get updated.

Fixed: "Commissions" page in the admin panel, page pagination does not work. #660

---

classes/admin/class-wcv-commissions-page.php

Update the vendor dropdown list in WC Vendors > Commissions page to use the ajax search for vendors.
Closes #656  .
1. Go to WC Vendors > Commissions page
2. Click on the Filter by Vendor dropdown, you should see a searchbox with instruction to type a few characters to search.
3. Type to search for a vendor. Check the dropdown list is updated with vendors matching your search characters
4. Select a vendor and click 'Filter', after page load, the commissions listed should only be those matching the selected vendor.

Fixed: Performance Issue: Vendor drop down on commissions page #656

---

classes/admin/class-product-meta.php

Closes #661 .
1. Assigned some of my admin products to a shop under WooCommerce-Products and save or update that product. 
2. Again open that product.
2. Now try to change them back to admin own products.

Fixed: Vendor assignment in product edit only recognizes vendors #661

---

classes/class-vendors.php

Closes #667 .
1. Go to a page and insert this shortcode - [wcv_pro_vendorslist]
2. Make sure that you have more than 15 vendors that have published products.
3. Scroll down to the pagination section and click page 2.
4. See that the page you can find the vendors data.

Fixed: Page 2 of the vendors pro list pagination returns a page 404 not found #667

---

classes/admin/class-product-meta.php

This fixes the search for both categories and products. 
Closes #678  .
1. Load fix, try to use category filter or product search
2. Show results
3.

Fixed: Product and category search not working on WooCommerce > Products

---

assets/js/admin/wcv-vendor-select.js

Closes #680 .
1. Update your WordPress to 5.5 and check for the latest jQuery.
2. Check the wp-admin.
3. This depreciation warning will not show up.

Fixed: Depreciated JS in WP 5.5 #680

---

classes/admin/class-product-meta.php

Avoid setting empty vendor if a vendor was not specified for the bulk edited products.
Closes #687 
1. Go to WordPress products dashboard
2. Bulk edit products and add a tag.
3. The edited products must still have the vendor displayed in the Vendor Store column

Bulk editing products and adding tags would cause the assigned vendor store on those bulk edited products to disappear #687

---

classes/admin/emails/class-emails.php

Closes #691 .
1. Log in as a vendor.
2. Mark shipped any of the orders.
3. It will fire email and you can handle that with this new filter. By default I've put is enabled.

Updated: Add a filter to handle customer email notification for the mark received shipping #691

---

assets/js/admin/wcv-vendor-select.js
classes/admin/class-product-meta.php
classes/admin/emails/class-emails.php

Add filter to change the minimum input length in vendors select dropdown.
Closes #688 
1. Add the filter below to functions.php
```
add_filter( 'wcvndors_vendor_select_minimum_input_length', function( $input_length ) {
$input_length = 2;
return $input_length;
});
```
2. Got to the admin dashboard and edit a product.
3. In the Vendor meta box, you should be able to search with 2 characters or the ones set in the `$input_length` in the filter.

Added: Filter to the vendor select minimum input length #688

---

classes/admin/class-product-meta.php

Allow searching vendors by store name, store slug, store description and seller information.
Closes #669 
1. Got to admin and edit a product
2.  In the Author metabox, search for a vendor by store name, slug, description or seller info. 
3. You should get results matching your search in the vendor selectbox

Updated: User store name or user id for vendor search in wp admin #669

---

classes/front/dashboard/class-vendor-dashboard.php
templates/dashboard/links.php

Closes #681 .
1. Use the advanced settings to delete data
2. Delete, reinstall, and reactivate plugins(marketplace and pro)
3. Without proceeding to the Setup wizard, try creating a page and use the shortcodes.

Fixed: Advanced option - Delete all data, requires the Wizard to be completed before users can use the shortcodes on the pages #681

---

classes/admin/class-wcv-commissions-page.php

Closes #702 .
1. Go to commissions and find a product that is listed. 
2. Delete the product permanently 
3. Check the commission's table, now you can see the product name without a link on it.

Deleted products don't have a title on the commissions table #702

---

classes/admin/settings/class-wcv-settings-payments.php

Removes the deprecated payments tab. 
Closes #704 .
1. Go to WC Vendors > Settings 
2. See payments tab is no longer available

Updated: Remove deprecated payments tab from settings

---

class-wc-vendors.php

Instead of using the final wp_die to stop the plugin running, switch to a more graceful admin notice. 
Closes #711.
1. Activate WC Vendors Marketplace without WooCommerce activated
2. See the new admin notice

Updated: Changed WooCommerce missing behaviour 

---

classes/admin/class-wcv-commissions-page.php

Updates code to remove deprecated call
Closes #709 
1. Ensure debugging is enabled
2. Delete a product that has had commission logged 
3. Check commissions table, no warnings.

Fixed: Deprecated WooCommerce call #709

---

classes/admin/class-admin-users.php
classes/admin/class-product-meta.php
classes/front/dashboard/class-vendor-dashboard.php

Closes #707 .
1.  Log in as a customer/another role
2. Check a single product page and see the "Add to wishlist" Button
3. The 'Add to wishlist" button must be visible when logged in as Customer/Vendor/Administrator or any other role.
4. If the product is already on the wishlist, the appropriate message must be visible when logged in as Customer/Vendor/Administrator or any other role

Fixed: Yith Conflict - Add to wishlist button does not show up for vendor roles. #707

---

classes/admin/class-product-meta.php

Fixed the vendor ID condition check 
Closes #724 
1.  Go to Products > bulk select products and edit them.
2. From the vendor drop-down, select a vendor and then click update.
3. See that the bulk edited product's assigned vendor has changed to the newly assigned vendor.

Fixed: Bulk assigning products to a vendor does not work #724

---

templates/emails/vendor-order-details.php

Closes #729 .
1. Check the pro plugin is enabled.
2. Put an order with the vendor product.
2. As admin user mark that order as processing.
3. Check vendor email order number has the link to the pro dashboard.

Updated: enhancement for New customer order vendor notification - Add link in the order number redirecting to /pro-dashboard/orders page #729

---

classes/admin/class-wcv-commissions-page.php

Closes #745 .
1. Place an order with the vendor product.
2. Mark that order as completed.
3. Now delete that ordder.
4. That error will not come.

Fixed: Call to a member function get_id() on boolean #745

---

classes/front/dashboard/class-vendor-dashboard.php

Closes #756 .
1. Login as admin.
2. Click on to open WC Vendors > Settings > Capabilities > General tab.
3. Untick the check box with label as "Allow vendors to view sales table on the frontend on the vendors dashboard page."
4. Click on to save the settings.
5. Log in as Vendor(make sure that the vendor has some sales.)
6. Click on to open Vendor Dashboard.
7. Check for the sales table. Now, Sales table is not visible.

Fixed: WC Vendors > Settings > Capabilities > General > Permissions > Vendor sales report table should get hidden as per permission set by admin. #756

---

class-wc-vendors.php
classes/admin/class-admin-users.php
classes/admin/class-product-meta.php
classes/admin/class-setup-wizard.php
classes/admin/class-wcv-admin-import-export.php
classes/admin/class-wcv-commissions-csv-exporter.php
classes/admin/class-wcv-commissions-page.php
classes/admin/class-wcv-commissions-sum-csv-exporter.php
classes/admin/emails/class-wc-notify-vendor.php
classes/admin/emails/class-wcv-vendor-notify-cancelled-order.php
classes/class-commission.php
classes/class-install.php
classes/class-vendors.php
classes/front/class-vendor-shop.php
classes/front/dashboard/class-vendor-dashboard.php
classes/includes/class-functions.php
classes/includes/class-wcv-shortcodes.php
classes/includes/wcv-template-functions.php
templates/dashboard/orders.php
templates/emails/plain/vendor-order-details.php
templates/emails/vendor-new-order.php
templates/emails/vendor-order-details.php

Closes #716 .
1. Check all the filter and action hooks with the new prefixes.
2. Old filter and action will still work but that will give you **PHP Deprecated** warning.

Updated: Action/Filter names need to be made consistent #716

---

classes/class-cron.php

PayPal adaptive payments were deprecated in version 1.8 of WC Vendors Marketplace. Cron class that scheduled these payments was still being initialised. Disable for future full removal in version 3.0. 
Closes #766.
1. Added check to the constructor to not initialise if paypal adaptive payment settings are not enabled and in use

Updated: Disabled cron system if deprecated PayPal settings not active

---

classes/front/dashboard/class-vendor-dashboard.php

Because  WC 3.6+ - Cart and other frontend functions are not included for REST requests. So we need to include wc-notice-functions.php it will resolve conflicts with Elementor Pro.
Closes #763.
1. Install and active WC Vendors Marketplace, Elementor, Elementor Pro
2. Create a page and edit page with Elementor. Add Products widget to the page.
3. GET http://yourdomain/wp-json/wp/v2/pages?per_page=20 API with per_page parameter more than 15
4. See no error.

Fixed: #763 Wordpress REST API (Pages asset) & WC Vendors Marketplace

---

readme.txt

Fixes readme.txt changelog entry required for wordpress.org release.

Update: readme.txt for release.

---

classes/front/account/class-wc-account-links.php
classes/front/signup/class-vendor-signup.php
classes/front/signup/views/html-vendor-signup.php
templates/dashboard/denied.php

- Added: `wcvendors_vendor_registration_label_css_classes` filter hook
1. Add an example code snippet below to your `functions.php`
2. Go to my-account
3. See `Apply to become a vendor?` label have class `example_css_class`
Code snippet: 
```
/**
* Add CSS class to apply for vendor label in a registration
*
* @param  string $class css classes.
* @return string
*/
function add_apply_vendor_label_css_class( $class ) {
$class .= 'example_css_class';
return $class;
}
add_filter( 'wcvendors_vendor_registration_apply_label_css_classes', 'add_apply_vendor_label_css_class', 10, 1 ); 
```

Added: Filter hook to add CSS classes to apply for vendor label

---

classes/admin/class-admin-menus.php

The 7th parameter of add_menu_page must be an integer in WordPress 6.0

Update menu page parameter

---

classes/admin/class-wcv-commissions-csv-exporter.php
classes/admin/settings/class-wcv-settings-commission.php
classes/class-queries.php
classes/front/dashboard/class-vendor-dashboard.php
classes/front/orders/class-orders.php
classes/includes/class-functions.php
templates/dashboard/orders.php
templates/orders/orders.php
templates/orders/table-body.php

- Updated: View order screen in sales report table in Vendor Dashboard
- Updated: Orders table view items in Vendor Dashboard
1. Login as vendor account
2. Go to Vendor Dashboard
3. Click Show Orders in the Sales Report table will see refund detail if the order has been refunded
4. Click View items in the Orders table will see refund detail if the order has been refunded

Update sales report to compatibility with refund update

---

changelog.txt
class-wc-vendors.php
package.json
readme.txt

Version 2.4.1 - 3rd March 2022
* Updated: Sales report with refund details (#822)
* Updated: Menu page parameter type in WordPress 6.0 (#826)
* Reverted: "Added: Log marketplace commissions to commissions table (#806)" (#832)
* Fixed: Undefined variable ids (#816)
* Fixed: Order export fails if the order has been deleted #813 (#814)

Prepare v2.4.1 for release

---

assets/css/wcv-store.css
assets/css/wcv-store.min.css
assets/css/wcv-store.scss
classes/front/dashboard/class-vendor-dashboard.php
templates/front/vendor-main-header.php
templates/front/vendor-mini-header.php

Closes #839.
- Change H1 tag to div
- Added: wcv-store.css/scss
1. Go to the product page or vendor store page
2. Check h1 tag on the Vendor shop name is gone and has been changed to div

Fixed: Duplicate H1 tag on products

---

changelog.txt
class-wc-vendors.php
package.json
readme.txt

Version 2.4.2 - 16th May 2022
* Updated: Dev tools (#842)
* Fixed: Vendor menu shows on Admin dashboard (#844)
* Fixed: Duplicate H1 tag on products (#840)
* Fixed: The colspan does not match in vendor dashboard (#838)

Prepare v2.4.2 for release

---

changelog.txt
class-wc-vendors.php
classes/admin/emails/class-wcv-admin-notify-product.php
package.json
readme.txt

- Prepare for the v2.4.4 release
- Fixed typo
**Version 2.4.4 - 24 November 2022**
* Fixed: Admin notify product email firing twice
* Fixed: New vendor list pagination doesn't work when using the display options grid or list. (#870)

Prepare for v2.4.4 release

---

assets/js/wcv-admin-quick-edit.js
classes/admin/class-product-meta.php

- Global $post variable return only one post, then the author is only author of the first post. So I use $wp_query to get authors on the list.
- Format code follow WPCS
1. Go to WP Dashboard → Products
2. Try to quick edit any product and see the vendor is selected correct vendor and not empty
3. Save and check the vendor is correct in both side : the list and in single product edit screen

Fixed: Vendor select box incorrect or empty

---

changelog.txt
class-wc-vendors.php
package.json
readme.txt

**Changelog:** 
* Added: Vulnerability reporting point of contact (#886)
* Fixed: Vendor selectbox incorrect or empty on product page (#885)

Prepare v2.4.6 for release
